version: "2"
services: 
  mongo:
    image: mongo:latest
    volumes:
      - ./mongodata:/data/db
    restart: always
  backend:
    build: ./packages/backend
    depends_on:
      - mongo
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./log/:/var/log/sslmanager/
  frontend:
    build: ./packages/frontend
    depends_on:
      - backend
    volumes:
      - ./log/:/var/log/nginx/
    ports:
      - "80:80"
    restart: always